{
	"0": "« Exponentialité alternative »",
	"2": "« Une jeune fille au QI d'or »",
	"4": "« Une jeune déesse au QI d'or »",
	"6": "Programme « Trou de Ver Virtuel »",
	"10": "Signe du gras : « Butter Spark »",
    "12": "Signe du gras : « Sweet Butter Spark »",
    "14": "Rébellion : « Orbes du passé »",
    "18": "Magie normande « Crise du Mont Saint-Michel »",
    "21": "Magie normande : « Shoot the Bretagne »",
	"22": "Art divin : « Art de la couture »",
    "24": "Art divin : « Art de la couture de poupées »",
	"26": "Signe primitif : « Être mono-neuronal »",
    "28": "Signe primitif : « Être bi-neuronal »",
    "29": "Signe primitif : « Neurone unique et infini »",
}