{
	"0": "« Exponentialité alternative »",
	"2": "« Une jeune fille au QI d'or »",
	"4": "« Une jeune déesse au QI d'or »",
	"6": "Programme « Trou de Ver Virtuel »",
	"10": "Signe du gras : « Butter Spark »",
    "12": "Signe du gras : « Sweet Butter Spark »",
    "14": "Rébellion : « Orbes du passé »",
    "18": "Magie normande « Crise du Mont Saint-Michel »",
    "21": "Magie normande : « Shoot the Bretagne »",
	"22": "Art divin : « Art de la couture »",
    "24": "Art divin : « Art de la couture de poupées »",
	"26": "Signe primitif : « Être mono-neuronal »",
    "28": "Signe primitif : « Être bi-neuronal »",
    "29": "Signe primitif : « Neurone unique et infini »",
	"30": "Frontière de la sagesse : « Spirale autodestructrice »",
    "32": "Frontière de la sagesse : « Spirale destructrice incommensurable »",
	"34": "Signe du chaos : « Floraison imprévue »",
    "36": "Signe du chaos : « Floraison imprévue et fatale »",
    "37": "Signe du chaos : « Fleurs d'annihilation »",
    "38": "« A vaincre sans péril, on triomphe sans gloire »",
	"58": "« Tissage de la réalité »",
    "60": "« Peut-on couper les fils du destin ? »",
	"62": "Pyrotechnie : « Festival estival »",
    "64": "Pyrotechnie : « Saxifrage Ryuukin »",
	"66": "Signe sacré : « Barrière de purification »",
	"69": "Signe sacré : « La pure flamme de la vérité »",
    "70": "Puissance maximale : « Moon Breaker »",
	"74": "« Point de non retour »",
    "76": "« La prêtresse du crépuscule »",
    "78": "Signe du Beurre Doux \" je sais pas\" ",
	"108": "« Mémoires de la haine et de la destruction »"
}