{
    "0": "Signe papillon « Mesure des minutes »",
    "2": "Signe papillon « Mesure à queue d’hirondelle »",
    "4": "Signe papillon « L’été qui bat son plein »",
    "6": "Signe papillon « Les battements d’ailes de la mi-été »",
    "8": "Signe de pluie « Pluie d’automne emprisonnante »",
    "10": "Signe de pluie « Pluie torrentielle maudite »",
    "12": "Signe de lame « Affûtage du couteau de cuisine de Yamanba »",
    "14": "Signe de lame « L’affûtage du couteau de cuisine Oni de Yamanba »",
    "16": "Signe d’épuisement des lames « Meurtrier de la montagne »",
    "18": "Signe d’épuisement des lames « Meurtrier sanguinaire de la montagne »",
    "20": "Signe de printemps « Printemps inattendu »",
    "22": "Signe du chien « Promenade du chien errant »",
    "24": "Signe du chien « Marche du Chien de Montagne »",
    "26": "Signe Tournoyant « Toupie Koma-Inu »",
    "29": "Signe Tournoyant « Courbe-toi et meurs »",
    "30": "Signe Koma « Souffle solitaire »",
    "34": "Signe de magie « Bodhi instantanée »",
    "36": "Signe de magie « Bodhi instantanée »",
    "38": "Signe de magie « Projectile golem »",
    "40": "Signe de magie « Projectile vivant animal »",
    "42": "Signe Jizo « Le salut criminel »",
    "44": "Signe Jizo « Le salut de l’enfer »",
    "46": "Signe du bambou « Danse de la lance en bambou »",
    "48": "Signe du bambou « Danse folle du bambou »",
    "50": "Signe du Zingiber mioga « Oublie ton nom »",
    "54": "Signe à feuilles larges « Festival des étoiles de Tanabata »",
    "58": "Bénédiction mioga « Derrière vous »",
    "62": "Signe de danse « Festival arrière »",
    "66": "Danse folle « Tengu-odoshi »",
    "68": "Danse folle « Frayeur-tengu endiablée »",
    "70": "Signe de derrière « Halo de la déesse secrète »",
    "73": "Signe de derrière « Le halo du dieu secret absolu »",
    "74": "Été caché « Brûlure par la chaleur estivale »",
    "76": "Été caché « Terre brûlée par une chaleur anormale et intense »",
    "78": "Automne caché « Mort par Famine »",
    "80": "Automne caché « La Préta de la brûlure anormale »",
    "82": "Hiver caché « Le bonhomme de neige noir »",
    "84": "Hiver caché « Bonhomme de neige des chutes de neige anormales »",
    "86": "Printemps caché « Le mage d'avril »",
    "88": "Printemps caché « Le mage noir des pétales tombant anormalement »",
    "90": "« Cerisier caché de la brise en fleurs »",
    "94": "« Glace de l’été cachée parfaite »",
    "98": "« Vent d’automne fou caché »",
    "102": "« Hiver extrême caché »",
    "106": "Danse du tambour « Puissantes acclamations »",
    "107": "Danse folle « La danse folle du soutien »",
    "108": "Danse des projectiles « Les typhons jumeaux »",
    "109": "10/100 « Le printemps volé »",
    "110": "20/100 « Espoir d'un printemps total »",
    "111": "30/100 « Tranchant d'une fleur gelée »",
    "112": "40/100 « Silencieuse danse fantômatique »",
    "113": "50/100 « Tourbillon de pétales »",
    "114": "60/100 « Synergie millénaire »",
    "115": "70/100 « Frontière entre l'inerte et le vivant »",
    "116": "« Resurrection Butterfly - 80/100 Reflowering - »",
    "117": "90/100 « Vitalité donnée au monde des morts »",
    "118": "« Perfect Cherry Blossom »"
}