{
    "0": "9 sign [Daiyousei Return]",
    "2": "9 sign [Daiyousei Strikes Back]",
    "4": "Fairy sign [Daiyousei Revenge]",
    "6": "Fairy sign [Daiyousei Final Revenge]",
    "8": "Fairy sign [Fairies Help]",
    "14": "Trick or Treat !",
    "16": "No Treat, Only Trick !",
    "18": "Throwing Knives around The World",
    "20": "Throwing Knives around ZA WARUDOOOO",
    "24": "Risk Sign [Wrong Timing Autocollect]",
    "26": "Jojo ref \"Stand Behind Me !\"",
    "28": "STANDO PAWA \"Hermit Coupler\"",
    "30": "Pure Destruction 2nd Try",
	"31": "Pure Destruction 3rd Try",
    "32": "Butterflies Passing Through Adversity",
    "36": "Flowering Gungnir",
	"38": "Flowering Gungnir",
    "40": "Immortal Scarlet Flowers of Illusion",
    "42": "Immortal Scarlet Flowers of Illusion",
    "44": "Evil Sign \"Yǎng Xiǎoguǐ\"",
    "45": "Evil Sign \"Gūhún Yěguǐ\"",
    "47": "Demonify \"Zǒuhuǒ Rùmó\"",
    "51": "Possession \"Corpse Tóngjī\"",
    "53": "Spirit Link \"Tōnglíng Yoshika\"",
    "55": "Taoist Sign \"Tao Fetal Movement\"",
    "59": "Thunder Arrow \"Gagouji's Cyclone\"",
    "60": "Thunder Arrow \"Gagouji's Cyclone\"",
    "61": "Thunder Arrow \"Gagouji's Tornado\"",
    "62": "Heaven Sign \"Rainy Iwafune\"",
    "64": "Heaven Sign \"Ame-no-Iwafune, Ascend to Heaven\"",
    "66": "Throwing Dishes \"Mononobe's Eighty Saké Cups\"",
    "70": "Blaze Sign \"Blazing Winds of Haibutsu\"",
    "72": "Blaze Sign \"Sakurai-ji in Flames\"",
    "74": "Saint Girl \"Oomonoimi's Dinner\"",
    "78": "Honor \"Colors of Twelve Levels\"",
    "80": "Honor \"Ranks of Twelve Levels\"",
    "82": "Hermit Sign \"Taoist of the Land of the Rising Sun\"",
    "84": "Hermit Sign \"Emperor of the Land of the Rising Sun\"",
    "86": "Summon \"Royal Clan's Chaotic Dance\"",
    "90": "Secret Treasure \"Armillary Sphere of Ikaruga-dera\"",
    "93": "Secret Treasure \"Prince Shotoku's Out-of-Place Artifact\"",
    "94": "Light Sign \"Halo of the Guse Kannon\"",
    "96": "Light Sign \"Guse Flash\"",
    "98": "Discernment \"Lasers of Seventeen Articles\"",
    "100": "Divine Light \"Honor the Avoidance of Defiance\"",
    "102": "\"Falling Stars on Divine Spirit Mausoleum\"",
    "104": "\"Newborn Divine Spirits\"",
    "106": "Unknown \"Will-o'-wisps in Unknown Orbit\"",
    "107": "Unknown \"Skyfish with Unknown Shape\"",
    "108": "Unknown \"Youkai Orb of Unknown Mechanics\"",
    "109": "First Duel \"Primate Danmaku Transformation\"",
    "110": "Second Duel \"Carnivorous Danmaku Transformation\"",
    "111": "Third Duel \"Avian Danmaku Transformation\"",
    "112": "Fourth Duel \"Amphibian Danmaku Transformation\"",
    "113": "Fifth Duel \"Scrolls of Frolicking Animals\"",
    "114": "Sixth Duel \"Tanuki's Monstrous School\"",
    "115": "Seventh Duel \"Wild Deserted Island\"",
    "116": "Transformation \"Pseudo-Exorcism of the Stupid Shrine Maiden\"",
    "117": "\"Mamizou Danmaku in Ten Transformations\"",
    "118": "Raccoon Sign \"Full Moon Pompokolin\"",
    "119": "Cherry Blossom Sign \"Cherry Blossom Blizzard Hell\"",
    "120": "Mountain Echo \"Yamabiko's Specialty Echo Demonstration\"",
    "121": "Poison Nail \"Undead Murderer\"",
    "122": "Taoist Sign \"TAO Fetal Movement ~Dao~\"",
    "123": "Vengeful Spirit \"Iruka's Thunder\"",
    "124": "Saint Girl \"Sun Goddess's Sacrifice\"",
    "125": "\"Divine Spirits' Universe\"",
    "126": "\"Wild Carpet\""
}