{
	"0": "« Alternative exponantiality »",
	"2": "« A young girl with a gold IQ »",
	"4": "« A young goddess with a gold IQ »",
	"6": "Program « Virtual Wormhole »",
	"10": "Grease sign : « Butter Spark »",
    "12": "Grease sign : « Sweet Butter Spark »",
    "14": "Rebellion : « Orbs from the past »",
    "18": "Normand magic « Crisis of Mont Saint-Michel »",
    "21": "Normand magic : « Shoot the Bretagne »",
	"22": "Divine art : « Art of sewing »",
    "24": "Divine art : « Art of sewing dolls »",
	"26": "Primitive sign : « Mono-neuronal being »",
    "28": "Primitive sign : « Bi-neuronal being »",
    "29": "Primitive sign : « Unique and infinite neuron »",
	"30": "Destruction : « Hakai »",
    "32": "Destruction : « ALL FICTION »",
	"34": "Chaos sign : « Unforseen blossom »",
    "36": "Chaos sign : « Unforseen and deadly blossom »",
    "37": "Chaos sign : « Annihilation flowers »",
    "38": "« Victory without risk is triumph without glory »",
	"42": "Heat sign « Slow baking »",
    "46": "Heat sign « Stealth embrace »",
    "50": "Change of phase « Boiling »",
    "54": "« Light leading to the absolute zero »",
	"58": "Lie « Death of Nozomia »",
    "60": "Lie « Can we cut the loom of fate? »",
	"62": "Pyrotechnics : « Charlotte's strange firework »",
    "64": "Pyrotechnics : « Perfect illusory firework »",
	"66": "Holy sign : « The Besta's purification barrier »",
	"69": "Holy sign : « The pure flame of truth »",
    "70": "Setting : « Explosive moon »",
	"74": "« Breakdown of the illusion »",
    "76": "« Round of applause »",
    "78G": "Know-how : « Production of divine salt »",
    "78S": "Know-how : « Production of pure butter »",
    "82G": "Non-Butter sign : « Salted sonar of Brest »",
    "82S": "Non-Butter sign : « Soft bridge of Tancarville »",
	"86G": "« Banner of a breton faction »",
	"86S": "« Normand menhir field »",
    "88G": "« Symbol of the traditionnal order »",
	"88S": "« Lands of ancestral memories »",
    "90G": "« Kouign amann's blessing »",
	"90S": "« Protection from Mont Saint-Michel »",
	"94G": "Divine authority « Grand Order of Salted Butter »",
	"94S": "Divine authority « Grand Order of Soft Butter »",
    "98G": "« Divine storm »",
	"98S": "« Divine radiance »",
    "101G": "« It only rains on sods »",
	"101S": "« The light casts shadows »",
    "102G": "Butter sign : « Praises of Salted Heavens »",
	"102S": "Butter sign : « Praises of Soft Heavens »",
    "104G": "Butter sign : « A prayer to the crystalline goddess »",
	"104S": "Butter sign : « A prayer to the plain goddess »",
	"106": "Probability « World tree of possibilities »",
	"107": "« Read the fucking formula »",
	"108": "« Memories of hatred and destruction »",
	"109": "Unholy sign « Scarlet Spears of the Heretic »",
	"110": "Illusion : « The cruel reality behind the novel »",
    "111": "Karaoke : « DEMONIC TRUTH »",
    "112": "Preparation « Ceremonial knife from Laguiole »",
    "113": "Blend : « Whisking the magic to make it homogeneous »",
    "114": "Frying pan sign : « Perfect cooking »",
    "115": "Devil : « Vampires' great banquet »",
    "116": "Goddess « Kurakomainu restaurant's dish of the day »",
    "117": "« Facts of Buttered Landings »",
    "118": "« Ultimated danmaku of a buttered tale »"
}