{
    "th10_ascii_stage_clear": "Termine",
    "th13_ascii_spell_game": "MODE DE JEU        %4d/%4d",
    "th14_ascii_bonus": "BONUS %.1f",
    "th10_ascii_ranking": "           Classement des resultats",
    "th13_ascii_credit": "Credit %d",
    "th06 cancel": "Annuler",
    "th11 Dialog Window 640": "Fenêtré (640×480)",
    "th11 Dialog Window 960": "Fenêtré (960×720)",
    "th11 Dialog Window 1280": "Fenêtré (1280×960)",
    "th06 windowed": "Fenêtré",
    "th08 Spell Resurrection": "« Résurrection »",
    "th13 spell nothing": "Rien...",
    "th14 Dialog 640": "640×480",
    "th14 Dialog 960": "960×720",
    "th14 Dialog 1280": "1280×960 (Recommandé)",
    "th06 colors": "Couleurs",
    "th10 Dialog Fullscreen": "Plein écran",
    "th11 Dialog Fullscreen 640": "Plein écran (640×480)",
    "th06 fullscreen": "Plein écran",
    "th07 fullscreen": "Plein écran (Rec.)",
    "th10 Dialog Always ask": "Toujours demander au démarrage",
    "th143 Trophy Format": "« %s »",
    "th07 Menu Start": "Commencer la partie",
    "th07 Menu Quit": "Quitter le jeu",
    "th07 Menu Extra Start": "Commencer l'Extra Stage",
    "th07 Menu Practice Start": "Sélectionner un niveau et commencer l'entraînement",
    "th10_ascii_stage_1": "Niveau 1",
    "th10_ascii_stage_2": "Niveau 2",
    "th10_ascii_stage_3": "Niveau 3",
    "th10_ascii_stage_4": "Niveau 4",
    "th10_ascii_stage_5": "Niveau 5",
    "th10_ascii_stage_6": "Niveau 6",
    "th16_ascii_score_spring": "Printemps",
    "th16_ascii_score_summer": "Ete",
    "th16_ascii_score_autumn": "Automne",
    "th16_ascii_score_winter": "Hiver",
    "th16_ascii_score_sp": "Pr",
    "th16_ascii_score_sm": "Et",
    "th16_ascii_score_at": "Au",
    "th16_ascii_score_wt": "Hi",
    "th10_ascii_score_empty": "%2d  %s  %9ld%d  ----/--/-- --:--  Niveau -  ---%",
    "th16_ascii_score_empty": "%2d  %s  %9ld%d  ----/--/-- --:-- Saison  Niveau -  ---%%",
    "th14_ascii_no_bonus": "PAS DE BONUS",
    "th13_ascii_spell_unknown": "SCORE        00  ----/----",
    "th13_ascii_spell_score": "SCORE %8d0  %4d/%4d",
    "th07 Menu Result": "Regarder les scores et l'historique des Cartes de sort",
    "th07 Menu Music Room": "Écouter de la musique",
    "th07 Menu Replay": "Regarder les replays",
    "th07 Menu Option": "Modifier les paramètres",
    "th07 Option Player": "Choisissez le nombres de vies initiales au début de la partie. (Par défaut : 3)",
    "th07 Option Graphic": "Changer la profondeur des couleurs. Le 32-bit semble être le plus beau.",
    "th07 Option BGM": "Changer la méthode pour jouer la musique de fond. (Par défaut : WAV)",
    "th07 Option Sound": "Choisir si vous voulez jouer avec les effets sonores.",
    "th07 Option Window Mode": "Changer de mode entre Plein écran et Fenêtré.",
    "th07 Option Slow Mode": "Ralentir le jeu quand beaucoup de balles sont à l'écran. (Aucun meilleur score ou replay ne sera enregistré)",
    "th07 Option Reset": "Réinitialiser les paramètres.",
    "th07 Option Key Config": "Configurer les contrôles.",
    "th07 Option Quit": "Quitter le menu des options.",
    "th07 Key Shot": "Choisir la touche pour Tirer/Valider.",
    "th07 Key Bomb": "Choisir la touche pour les bombes/Annuler.",
    "th07 Key Slow": "Choisir la touche pour ralentir les mouvements.",
    "th07 Key Skip": "Choisir la touche pour passer les dialogues.",
    "th07 Key Pause": "Choisir la touche pour mettre en Pause.",
    "th07 Key Up": "Choisir la touche pour se déplacer vers le haut.",
    "th07 Key Down": "Choisir la touche pour se déplacer vers le bas.",
    "th07 Key Left": "Choisir la touche pour se déplacer vers la gauche.",
    "th07 Key Right": "Choisir la touche pour se déplacer vers la droite.",
    "th07 Key ShotSlow": "Déplacez-vous plus lentement en maintenant la touche de tir enfoncée.",
    "th07 Key Reset": "Réinitialiser les paramètres.",
    "th07 Key Quit": "Quitter la configuration des contrôles.",
    "th08 Menu Spell Practice": "S'entraîner sur une Carte de sort contre un adversaire.",
    "th08 Option BGM Volume": "Ajuster le volume de la musique de fond.",
    "th08 Option SE Volume": "Ajuster le volume des effets sonores.",
    "th08 Spell Practice Description": "Niveau  Capture/Essais/Total (()Total avec tous les personnages)",
    "th08 Spell Practice Percentages": "Taux de capture  (Personnage/Global)",
    "th09 Menu Story Start": "Commencer le mode Histoire",
    "th09 Menu Extra Start": "Commencer le mode Extra",
    "th09 Menu Match Start": "Commencer avec le mode JcJ, vs. ORDI, ou Spectateur.",
    "th09 Menu Replay": "Rejouer les replays",
    "th09 Menu Result": "Voir les meilleurs scores",
    "th09 Menu Music Room": "Entrer dans la salle de musique",
    "th09 Option BGM": "Changer la méthode pour jouer la musique de fond. *Le MIDI n'est pas encore supporté actuellement.",
    "th09 Option Key Config": "Modifier les contrôles.",
    "th09 Key Side": "Choisissez J1 ou J2.",
    "th09 Key Control Type": "PAD 1 ou 2 : Utiliser la manette ; Entier, Gauche ou Droite : Utiliser le clavier",
    "th09 Key Charge Type": "Modifier le comportement du bouton de charge.",
    "th09 Key Shot": "Choisir la touche pour Tirer.",
    "th09 Key Bomb": "Choisir la touche pour les bombes.",
    "th09 Key Slow": "Choisir le ralentissement ou la charge.",
    "th08 Music Room spoiler 1": "*** NOTE ***",
    "th08 Music Room spoiler 2": "Cette musique n'a pas encore été jouée dans le jeu.",
    "th08 Music Room spoiler 3": "Si vous ne voulez pas écouter la musique ou lire les commentaires,",
    "th08 Music Room spoiler 4": "Il est recommandé de vous éloigner d'ici au plus vite.",
    "th08 Music Room spoiler 5": "　",
    "th08 Music Room spoiler 6": "(Aussi, notez que vous pouvez aussi appuyer sur OK ici et sur les autres musiques",
    "th08 Music Room spoiler 7": "pour lire le commentaire et jouer le thème, donc faites attention.)",
    "th09 Music Room spoiler 1": "***** NOTE *****",
    "th09 Music Room spoiler 2": "Cette musique n'a pas encore été jouée dans le jeu.",
    "th09 Music Room spoiler 3": "Vous pouvez écouter un extrait, mais les titres de musiques ne peuvent pas être lus.",
    "th10 Music Room spoiler 1": "<c$**Cette musique n'a pas encore été jouée dans le jeu.**$>",
    "th10 Music Room spoiler 2": "<c$Les commentaires peuvent contenir des spoilers.$>",
    "th10 Music Room spoiler 3": "<c$Voulez-vous quand même jouer la musique ?$>",
    "th10 Music Room spoiler 4": "<c$Si vous voulez la jouer, appuyez encore une fois sur OK.$>",
    "th10 Music Room spoiler 5": "<c$Si vous ne le voulez pas, déplacez le curseur.$>",
    "th143 Trophy Get": "Surnom obtenu :",
    "th10 Dialog Prompt": "Choisissez un mode d'affichage.",
    "th11 Dialog Game Start": "Démarrer",
    "th14 Dialog Prompt": "Sélectionnez la résolution :",
    "th14 Dialog Always ask": "Toujours demander",
    "th14 Dialog Fullscreen": "Jouer en plein écran",
    "th06 up": "Haut ",
    "th06 down": "Bas ",
    "th06 left": "Gauche ",
    "th06 right": "Droite ",
    "DirectInput fix": "Utiliser DirectInput",
    "DirectInput fix, layout-dependent shot key": "Utiliser DirectInput (Touche de tir : %c)",
    "th06 vertex": "Ne pas utiliser les tampons vertex",
    "th06 fog": "Ne pas utiliser le brouillard",
    "th06 16bit textures": "Textures 16-bit",
    "th06 Gouraud shading": "Supprimer l'utilisation de l'ombrage de Gouraud",
    "th06 color composition": "La composition des couleurs n'est pas appliquée aux textures",
    "th06 rasterizer mode": "Démarrer en \"reference rasterizer\"",
    "th06 clear buffer": "Nettoyer le buffer en rechargement d'image",
    "th06 minimum graphics": "Afficher les graphismes minimum requis",
    "th06 depth test": "Désactiver le test de profondeur",
    "th06 force frame": "Forcer les 60 images par seconde",
    "th06 full rate": "1/1 (Par défaut)",
    "th06 half rate": "1/2",
    "th06 third rate": "1/3",
    "th06 32bits mode": "32-bit",
    "th06 16bits mode": "16-bit",
    "th06 accept": "Valider",
    "th06 screen mode": "Affichage",
    "th06 refresh rate": "Taux de rafraîchissement d'images",
    "th06 pad X axis": "Manette : Axe X (1-1000)",
    "th06 pad Y axis": "Manette : Axe Y (1-1000)",
    "th06 check pad": "Vérifier les entrées de la manette",
    "th06 config saved caption": "OK",
    "th06 config saved text": "Configuration sauvegardée.",
    "th07 16bits textures": "Forcer l'utilisation de textures 16-bit",
    "th07 BGM memory": "Précharger la musique de fond en mémoire",
    "th07 draw screen": "Redessiner l'ATH à chaque image",
    "th07 VSync": "Désactiver la synchronisation verticale",
    "th07 low effects": "Minimum",
    "th07 medium effects": "Moyen",
    "th07 high effects": "Maximum (Rec.)",
    "th07 32bits mode": "32-bit (Par défaut)",
    "th07 effect quality": "Qualité des effets :",
    "th08 fog": "Désactiver le brouillard (Non recommandé)",
    "th08 color composition": "Ne pas utiliser la compositions des couleurs des textures (INTERDIT)",
    "th08 depth test": "Désactiver les tests de profondeur (Non recommandé)",
    "th08 rasterizer mode": "Démarrer en \"reference rasterizer\" (INTERDIT)",
    "th08 VSync": "Désactiver la synchronisation verticale (Non recommandé)",
    "th09 full rate": "Aucun (Par défaut)",
    "th09 1P controller": "Manette J1",
    "th09 2P controller": "Manette J2",
    "th09 gamepad 1": "Manette 1",
    "th09 gamepad 2": "Manette 2",
    "th09 all keyboard": "Clavier complet",
    "th09 left side keyboard": "Gauche",
    "th09 right side keyboard": "Droite",
    "th09 no save": "Quitter sans sauvegarder",
    "th09 save": "Sauvegarder et quitter",
    "th10 faith meter": "Montrer la barre de foi près du joueur",
    "th10 screen mode": "Affichage",
    "th10 always ask": "Toujours demander",
    "th10 slowshot": "Focus en tirant",
    "th11 input latency": "Temps de latence",
    "th11 stable input": "Stable (Si l'entrée ne marche pas souvent)",
    "th11 normal input": "Normal (Peu d'utilisation du CPU)",
    "th11 automatic input": "Automatique (Détecte la latence la plus courte) *Par défaut",
    "th11 fast input": "Rapide (Si Automatique ne fonctionne pas correctement)",
    "th11 input description": "Sélectionnez le type de latence pour un temps de réponse rapide.\n\"Stable\" et \"Normal\" répondent à l'entrée donnée lors de l'image précédente.\n\"Automatique\" va tenter de donner la latence la moins élevée possible.\n\"Rapide\" va donner des performances similaires à \"Automatique,\" mais la vidéo peut être distordue.\n*Ne marche pas avec les paramètres de taux de rafraîchissement d'image autre que \"No skip\"*",
    "th11 always ask": "Toujours demander au démarrage",
    "th11 sensitivity description": "Si l'entrée directionnelle est lente, augmentez la sensibilité.\n(Par défaut : 600)",
    "th11 joypad sensitivity": "Sensibilité de la manette",
    "th11 default": "Réinitialiser aux options par défaut",
    "th06_ascii_centered_stage": "NIVEAU %d",
    "th06_ascii_centered_stage_final": "NIVEAU FINAL",
    "th06_ascii_centered_stage_extra": "NIVEAU EXTRA",
    "th06_ascii_centered_stage_demo": "PARTIE DE DEMONSTRATION",
    "th06_ascii_centered_spell_bonus": "Bonus de carte de sort !",
    "th06_ascii_fullpower": "Puissance maximale !",
    "th06_ascii_bonus_format": "BONUS %8d",
    "th06_ascii_clear_header": "Niveau termine",
    "th06_ascii_clear_header_all": "Reussite totale !",
    "th06_ascii_clear_bonus_stage": "Niveau x 1000 = %5d",
    "th06_ascii_clear_bonus_power": "Puissance x 100 = %5d",
    "th06_ascii_clear_bonus_graze": "Frolement x 10 = %5d",
    "th06_ascii_clear_bonus_point": "   x Objet de points %3d",
    "th06_ascii_clear_bonus_player": "Joueur    = %8d",
    "th06_ascii_clear_bonus_bomb": "Bombes    = %8d",
    "th06_ascii_clear_bonus_easy": "Mode Facile     x0,5",
    "th06_ascii_clear_bonus_normal": "Mode Normal     x1,0",
    "th06_ascii_clear_bonus_hard": "Mode Difficile  x1,2",
    "th06_ascii_clear_bonus_lunatic": "Mode Lunatique  x1,5",
    "th06_ascii_clear_bonus_extra": "Mode Extra      x2,0",
    "th06_ascii_clear_bonus_penalty_0.5": "Penalite joueur x0,5",
    "th06_ascii_clear_bonus_penalty_0.2": "Penalite joueur x0,2",
    "th06_ascii_clear_bonus_total": "Total     = %8d",
    "th06_ascii_replay_header": "No.  Nom       Date    Joueur  Mode",
    "th06_ascii_replay": "%s %8s  %8s %-7s  %-7s",
    "th06_ascii_replay_save_header": "No.  Nom     Date    Joueur  Score",
    "th06_ascii_replay_save_empty": "No.%.2d -------- --/--/-- -------          0",
    "th06_ascii_replay_save": "No.%.2d %8s %8s %7s %10d",
    "th06_ascii_2_digit_number_format": "No.%2d",
    "th06_ascii_replay_user": "Joueur",
    "th06_ascii_reimu_a": "ReimuA",
    "th06_ascii_reimu_b": "ReimuB",
    "th06_ascii_marisa_a": "MarisaA",
    "th06_ascii_marisa_b": "MarisaB",
    "th06_ascii_easy": "Facile",
    "th06_ascii_normal": "Normal",
    "th06_ascii_hard": "Difficile",
    "th06_ascii_lunatic": "Lunatique",
    "th06_ascii_extra": "Extra",
    "th06_ascii_replay_stage_header": "Niveau DernierScore",
    "th06_ascii_replay_stage_empty": "%-6s  ---------",
    "th06_ascii_replay_stage": "%-6s %10d",
    "th06_ascii_replay_stage_1": "Niveau 1",
    "th06_ascii_replay_stage_2": "Niveau 2",
    "th06_ascii_replay_stage_3": "Niveau 3",
    "th06_ascii_replay_stage_4": "Niveau 4",
    "th06_ascii_replay_stage_5": "Niveau 5",
    "th06_ascii_replay_stage_6": "Niveau 6",
    "th06_ascii_replay_stage_extra": "Extra",
    "th06_ascii_result_clear": "(C)",
    "th165_ascii_replay_sun": "   Dim",
    "th165_ascii_replay_mon": "   Lun",
    "th165_ascii_replay_tue": "   Mar",
    "th165_ascii_replay_wed": "   Mer",
    "th165_ascii_replay_thu": "   Jeu",
    "th165_ascii_replay_fri": "   Ven",
    "th165_ascii_replay_sat": "   Sam",
    "th165_ascii_replay_sun2": "2e Dim",
    "th165_ascii_replay_mon2": "2e Lun",
    "th165_ascii_replay_tue2": "2e Mar",
    "th165_ascii_replay_wed2": "2e Mer",
    "th165_ascii_replay_thu2": "2e Jeu",
    "th165_ascii_replay_fri2": "2e Ven",
    "th165_ascii_replay_sat2": "2e Sam",
    "th165_ascii_replay_sun3": "3e Dim",
    "th165_ascii_replay_mon3": "3e Lun",
    "th165_ascii_replay_tue3": "3e Mar",
    "th165_ascii_replay_wed3": "3e Mer",
    "th165_ascii_replay_thu3": "3e Jeu",
    "th165_ascii_replay_fri3": "3e Ven",
    "th165_ascii_replay_sat3": "3e Sam",
    "th165_ascii_replay_diary": "  Agenda",
    "th06 Bomb Reimu A": "Amulette spirituelle « Sceau des songes »",
    "th06 Bomb Reimu B": "Amulette onirique « Cercle de scellement du mal »",
    "th06 Bomb Marisa A": "Amulette magique « Rêverie de poussière d’étoile »",
    "th06 Bomb Marisa B": "Amulette d’amour « Éclat magistral »",
    "th07 Bomb Reimu A unfocused": "Signe de l’esprit « Sceau des songes – étendu »",
    "th07 Bomb Reimu A focused": "Signe de l’esprit « Sceau des songes – Concentré »",
    "th07 Bomb Reimu B focused": "Signe de rêve « Barrière duplex »",
    "th07 Bomb Marisa A focused": "Signe magique « Voie lactée »",
    "th07 Bomb Marisa B unfocused": "Signe de l’amour « Laser non-directionnel »",
    "th07 Bomb Sakuya A unfocused": "Signe d’illusion « Indiscriminé »",
    "th07 Bomb Sakuya A focused": "Signe d’illusion « Poupée tueuse »",
    "th07 Bomb Sakuya B unfocused": "Signe du temps « Carré parfait »",
    "th07 Bomb Sakuya B focused": "Signe du temps « Carré privé »",
    "th08 Bomb Reimu": "Signe spirituel « Sceau des songes »",
    "th08 Bomb Reimu Last": "Esprit divin « Sceau des songes – Instantané »",
    "th08 Bomb Yukari": "Signe de bordure « Quadruple barrière »",
    "th08 Bomb Yukari Last": "Bordure « Quadruple barrière de la nuit impérissable »",
    "th08 Bomb Marisa Last": "Canon-magique « Éclat final »",
    "th08 Bomb Alice": "Signe magique « Sacrifice artistique »",
    "th08 Bomb Alice Last": "Magipulation « Retour à l’inanimé »",
    "th08 Bomb Sakuya Last": "Inhumallusion « Tueur fantôme dans la brume nocturne »",
    "th08 Bomb Remilia": "Signe écarlate « Le château rouge sans nuit »",
    "th08 Bomb Remilia Last": "Magie écarlate « Démon écarlate »",
    "th08 Bomb Youmu": "Signe humain « Taillade du monde présent »",
    "th08 Bomb Youmu Last": "Oni Humain « L’abîme de l’éternel futur »",
    "th08 Bomb Yuyuko": "Signe de mort « Cauchemar atroce »",
    "th08 Bomb Yuyuko Last": "Papillon mortel « Sommeil éternel au pays des rêves »",
    "th08 Spell Dissolve": "« Dissolution du sort »",
    "th06 Stats ReimuA": "Reimu Hakurei (Esprit)   ",
    "th06 Stats ReimuB": "Reimu Hakurei  (Rêve)   ",
    "th06 Stats MarisaA": "Marisa Kirisame (Magie) ",
    "th06 Stats MarisaB": "Marisa Kirisame (Amour)",
    "th16 full rate": "Aucun (Par défaut)",
    "th16 Dialog Fullscreen": "Plein écran",
    "th17 Trophy Get": "Succès obtenu :",
    "th16 half rate": "1/2",
    "th16 third rate": "1/3",
    "th16 refresh rate": "Saut d’image (frameskip)",
    "th16 no save": "Quitter sans sauvegarder",
    "th16 slowshot": "Concentration lors du tir",
    "th16 input latency": "Latence de l’entrée",
    "th16 stable input": "Stable (Si l’entrée ne fonctionne pas souvent)",
    "th16 normal input": "Normal (Faible utilisation du CPU)",
    "th16 automatic input": "Automatique (Détecte la latence la plus courte) *Par défaut",
    "th16 fast input": "Rapide (Si Automatique ne fonctionne pas correctement)",
    "th16 input description": "Sélectionnez le type de latence pour un temps de réponse rapide.\n“Stable” et “Normal” répondent à l’entrée donnée lors de l’image précédente.\n“Automatique” va tenter de donner la latence la moins élevée possible.\n“Rapide” va donner des performances similaires à “Automatique,” mais la vidéo peut être distordue.\n*Ne fonctionne pas avec les paramètres de taux de rafraîchissement d’image autre que “No skip”*",
    "th16 Dialog Always ask": "Toujours demander au démarrage",
    "th16 sensitivity description": "Si l'entrée directionnelle est lente, augmentez la sensibilité.\n(Par défaut : 600)",
    "th16 joypad sensitivity": "Sensibilité de la manette",
    "th16 default": "Revenir au paramètres par défaut",
    "th07 Spell Result Character Select": "%s  Total %3d / Acquis %3d (Changer de personnage ↓↑)",
    "th08 Spell Result Character Select": "%3d/%3d（Changer de personnage ↓↑）",
    "th08 Stats Total (All Characters)": "Tous les personnages",
    "th08 Stats Time Since Startup": "<tl$Temps depuis le démarrage>  %.2d:%.2d:%.2d",
    "th08 Stats Total Playtime": "<l$Temps de jeu total>  %.2d:%.2d:%.2d",
    "th07 Stats SakuyaA": "Sakuya Izayoi (Illusion) ",
    "th07 Stats SakuyaB": "Sakuya Izayoi (Temps)  ",
    "th07 Stats Total (All Characters)": "Tous les personnages    ",
    "th07 Stats Time Since Startup": "<tl$Temps depuis le démarrage>  %.2d:%.2d:%.2d",
    "th07 Stats Total Playtime": "<l$Temps de jeu total>  %.2d:%.2d:%.2d",
    "th07 Stats Header Total": "Total",
    "th08 Stats Reimu & Yukari": "Reimu & Yukari",
    "th08 Stats Marisa & Alice": "Marisa & Alice",
    "th08 Stats Sakuya & Remilia": "Sakuya & Remilia",
    "th08 Stats Youmu & Yuyuko": "Youmu & Yuyuko",
    "th08 Stats Reimu": "Reimu Hakurei",
    "th08 Stats Yukari": "Yukari Yakumo",
    "th08 Stats Marisa": "Marisa Kirisame",
    "th08 Stats Alice": "Alice Marigold",
    "th08 Stats Sakuya": "Sakuya Izayoi",
    "th08 Stats Remilia": "Remilia Scarlet",
    "th08 Stats Youmu": "Youmu Konpaku",
    "th08 Stats Yuyuko": "Yuyuko Saigyouji",
    "th08 Stats Play Count": "Nombre de parties",
    "th08 Spell Practice Easy Mode": "Entraînement aux sorts (Facile)",
    "th08 Spell Practice Normal Mode": "Entraînement aux sorts (Normal)",
    "th08 Spell Practice Hard Mode": "Entraînement aux sorts (Difficile)",
    "th08 Spell Practice Lunatic Mode": "Entraînement aux sorts (Démentiel)",
    "th08 Spell Practice Extra Mode": "Entraînement aux sorts (Extra)",
    "th08 Spell Practice List Description": "Acquises / Défiées (Total dans l’histoire principale)",
    "th08 Spell Practice Owner/Difficulty Line": "Joueur  %s　　%s %s",
    "th08 Spell Practice Last Word": "Entraînement aux sorts (Dernier mot)",
    "th08 Spell Practice Highscore Title": "Acquises / Défiées [Score total]　%s　tous personnages confondus",
    "th08 Stats Practice": "Entraînements  %6d %6d %6d %6d %6d %6d",
    "th08 Stats Clear Count": "Nombre de parties 1CC  %6d %6d %6d %6d %6d %6d",
    "th08 Stats Continue": "Continues utilisés  %6d %6d %6d %6d %6d %6d",
    "th07 Stats Clear Count": "Nombre de parties 1CC  %6d %6d %6d %6d %6d %6d",
    "th07 Stats Clear Count +Phantasm": "Nombre de parties 1CC  %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Continue": "Continues utilisés         %6d %6d %6d %6d %6d %6d",
    "th07 Stats Continue +Phantasm": "Continues utilisés         %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Practice": "Entraînements              %6d %6d %6d %6d %6d %6d",
    "th07 Stats Practice +Phantasm": "Entraînements            %6d %6d %6d %6d %6d %6d %6d",
    "th07 Stats Retries": "Réessais                       %6d %6d %6d %6d %6d %6d",
    "th07 Stats Retries +Phantasm": "Réessais                       %6d %6d %6d %6d %6d %6d %6d",
    "th08 Spell Practice Comment": "Commentaire sur la carte",
    "th08 Spell Practice Last Spell": "Dernier",
    "th06 BGM In-game format": "♪%s",
    "th07 Stats Play Count": "Nombre de parties          Facile Norm. Dur. Dém. Extra Total",
    "th07 Stats Play Count +Phantasm": "Nombre de parties          Facile Norm. Dur. Dém. Extra Phant. Total",
    "th08 Spell Condition Line 1 205": "Sélectionnable lors de l'acquisition d'au moins 7 cartes de sort supplémentaires.",
    "th08 Spell Condition Line 2 205": "　　　　　　　Obtenu.",
    "th08 Spell Condition Line 1 206": "Sélectionnable lorsque Normal FinalB est terminé avec 2 personnages ou plus.",
    "th08 Spell Condition Line 2 206 207 209": "　　　　　　　Quelle que soit la difficulté.",
    "th08 Spell Condition Line 1 207": "Sélectionnable lorsque Normal FinalB est terminé avec 3 personnages ou plus.",
    "th08 Spell Condition Line 1 208": "Sélectionnable lorsque 50 cartes de sort acquises en mode Spell Practice.",
    "th08 Spell Condition Line 2 208 211 217 220": "　　　　　　　Tous les personnages.",
    "th08 Spell Condition Line 1 209": "Sélectionnable lorsque Normal FinalB est terminé avec 4 personnages ou plus.",
    "th08 Spell Condition Line 1 210": "Sélectionnable lors de l'acquisition du No.%.3d",
    "th08 Spell Condition Line 1 211": "Sélectionnable lorsque 15 cartes de sort acquises en mode Spell Practice.",
    "th08 Spell Condition Line 1 212": "Sélectionnable lors de l'acquisition du No.%.3d,%.3d",
    "th08 Spell Condition Line 2 212": "　　　　　　　et lorsque est vu No.%.3d au moins une fois.",
    "th08 Spell Condition Line 1 213": "Sélectionnable lors de l'acquisition du No.%.3d,%.3d,%.3d",
    "th08 Spell Condition Line 2 213 214 222": "　　　　　　　Aucune acquisition nécessaire.",
    "th08 Spell Condition Line 1 214": "Sélectionnable lors de l'acquisition du No.%.3d,%.3d,%.3d,%.3d",
    "th08 Spell Condition Line 2 215": "　　　　　　　toutes les cartes de sort sont acquises.",
    "th08 Spell Condition Line 1 215": "Sélectionnable lorsque Normal est terminé avec Marisa (Solo).",
    "th08 Spell Condition Line 1 216": "Sélectionnable lorsque Hard ou Lunatique est terminé avec Reimu (Solo).",
    "th08 Spell Condition Line 2 216": "　　　　　　　Dernière scène du FinalB.",
    "th08 Spell Condition Line 1 217": "Sélectionnable lorsque 120 cartes de sort acquises en mode Spell Practice.",
    "th08 Spell Condition Line 1 218": "Sélectionnable lorsque Normal FinalB est terminé avec 6 personnages ou plus.",
    "th08 Spell Condition Line 2 218": "　　　　　　　",
    "th08 Spell Condition Line 1 219": "Sélectionnable lorsque l'Extra terminé avec au moins 3 personnages.",
    "th08 Spell Condition Line 1 220": "Sélectionnable lorsque 30 cartes de sort acquises en mode Spell Practice.",
    "th08 Spell Condition Line 1 221": "Sélectionnable lorsque Lunatic est terminé.",
    "th08 Spell Condition Line 2 221": "　　　　　　　Sans utiliser aucun continues.",
    "th08 Spell Condition Line 1 222": "Sélectionnable lorsque toutes les Last Words sont vus au moins une fois.",
    "th18 Ability Unlock": "Carte de capacité débloquée :",
    "th18 Trophy Get": "Succès déverrouillé :",
    "th18 card unobtained": "Vous n'avez pas encore débloqué ceci.",
    "th18 card unavailable": "Indisponible dans la démo.",
    "th18 screen mode": "Définition de l'écran",
    "th18 Dialog Window 640": "Fenêtré 640×480",
    "th18 Dialog Window 960": "Fenêtré 960×720",
    "th18 Dialog Window 1280": "Fenêtré 1280×960",
    "th18 Dialog Window 1920": "Fenêtré 1920×1440",
    "th18 Dialog Window 2560": "Fenêtré 2560×1920",
    "th18 Dialog Fullscreen 640": "Plein-écran 640×480",
    "th18 Dialog Fullscreen 960": "Plein-écran 960×720",
    "th18 Dialog Fullscreen 1280": "Plein-écran 1280×960",
    "th18 Dialog Borderless": "Fenêtre plein-écran sans bordures",
    "th18 Dialog Borderless DOT": "Fenêtre sans bordure DOT BY DOT (recommandé)",
    "th18_ascii_shop_money": "Fonds  %d  (+%d)",
    "th18_ascii_shop_cost": "Cout %d",
    "th18_ascii_menu_quit": "Quitter",
    "th18_ascii_menu_default": "Valeurs par defaut",
    "th18_ascii_menu_window": "Fenetre",
    "th18_ascii_menu_fullscreen": "Plein-ecran",
    "th18_ascii_menu_borderlessdbd": "         Sans bords pt/pt",
    "th18_ascii_menu_borderless": "     Sans bordures",
    "th18_ascii_menu_keyconfig": "Configuration des touches",
    "th18_ascii_menu_bgm_vol": "Vol. musique",
    "th18_ascii_menu_se_vol": "Vol. effets",
    "th18_ascii_menu_manual": "Manuel",
    "th18_ascii_menu_option": "Options",
    "th18_ascii_menu_pause": "Pause",
    "th18_ascii_ability_slot": "Emplacement %d",
    "th18_ascii_menu_screen": "Affichage",
    "th18_ascii_menu_keyboard": "Clavier",
    "th18_ascii_menu_directinput": "DirectInput",
    "th18_ascii_menu_xinput": "XInput",
    "th18_ascii_menu_music_room": "Auditorium",
    "th18_ascii_menu_replay": "Reprise video",
    "th18_ascii_menu_practice": "Entrainement",
    "th18_ascii_menu_spell_practice": "Pratique des sorts    ",
    "th18_ascii_menu_player_data": "Donnees",
    "th18_ascii_menu_bomb": "Bombe",
    "th18_ascii_menu_slow": "Concentration",
    "th18_ascii_menu_item": "Objet",
    "th18_ascii_menu_change": "Changement",
    "th18_ascii_menu_game_start": "Commencer",
    "th18_ascii_menu_extra_start": "Commencer extra ",
    "th18_ascii_menu_shot": "Tir",
    "th07 Stats Header Easy": "Facile",
    "th07 Stats Header Normal": "Normal",
    "th07 Stats Header Hard": "Difficile",
    "th07 Stats Header Lunatic": "Lunatique",
    "th07 Stats Header Extra": "Extra",
    "th07 Stats Header Phantasm": "Fantasme",
    "th07 Supernatural Border": "Barriere surnaturelle !!",
    "th07 CherryPoint Max": "Points de cerisier au max !",
    "th07 Border Bonus Format": "Bonus barriere %7d",
    "th06 DirectInput": "Ne pas utiliser DirectInput pour les entrées",
    "th07 DirectInput": "Ne pas utiliser DirectInput pour les entrées",
    "th16 save": "Sauvegarder et quitter",
    "th07 Stage Clear": "Niveau termine",
    "th07 All Clear": "Reussite totale",
    "th07 Clear Bonus Format": "Reussi = %8d",
    "th07 Clear Point Items Format": "Points = %8d",
    "th07 Clear Graze Format": "Frole. = %8d",
    "th07 Clear Cherry Format": "Ceris. = %8d0",
    "th07 Clear Bonus Life Format": "Vies   =%9d",
    "th07 Clear Bonus Bomb Format": "Bombe = %8d",
    "th07 Clear Easy Multiplier": "Facile       *0,5",
    "th07 Clear Normal Multiplier": "Normal       *1,0",
    "th07 Clear Hard Multiplier": "Difficile    *1,2",
    "th07 Clear Lunatic Multiplier": "Lunatique    *1,5",
    "th07 Clear Extra Multiplier": "Extra        *2,0",
    "th07 Clear Phantasm Multiplier": "Fantasme     *2,0",
    "th07 Clear Player Penalty*0.5": "Penalite vie  *0,5",
    "th07 Clear Player Penalty*0.2": "Penalite vie  *0,2",
    "th07 Clear Player Penalty*0.1": "Penalite vie  *0,1",
    "th07 Clear Player Penalty*0.05": "Penalite vie  *0,05",
    "th07 Clear Total Score Format": "Total = %8d0",
    "th08 Clear Time Orbs Format": "Temps = %8d0",
    "th08 Clear Human Format": "< -80%% = %3d.%.2d%%",
    "th08 Clear Youkai Format": ">  80%% = %3d.%.2d%%",
    "th08 Clear Last Time Format": "Dernier temps     = %2d:%.2d",
    "th08 Clear Night Bonus": "Bonus de nuit",
    "th08 config": "Touhou Eiyashou - Programme personnalisé d'environnement",
    "th06 config": "Touhou Koumakyou - Programme personnalisé d'environnement",
    "th07 config": "Touhou Youyoumu - Programme personnalisé d'environnement",
    "th09 config": "Touhou Kaeidzuka - Programme personnalisé d'environnement",
    "th095 config": "Touhou Bunkachou - Programme personnalisé d'environnement"
}