{
    "th16_01": "Le ciel où les pétales de cerisiers virevoltent vers le bas",
    "th16_02": "Une étoile de l'espoir se lève dans le ciel bleu",
    "th16_03": "Le rêve d'une fée à la mi-été",
    "th16_04": "Le vent incolore sur la montagne Youkai",
    "th16_05": "Rencontre en haute montagne",
    "th16_06": "Nage dans une mer aux couleurs de cerisiers en fleurs",
    "th16_07": "Un tandem de bêtes divines",
    "th16_08": "Voyageur blanc illusoire",
    "th16_09": "Le chapeau de paille magique Jizo",
    "th16_10": "La porte interdite mène-t-elle à ce monde ou à l'au-delà ?",
    "th16_11": "Les danseurs de soutien fous",
    "th16_12": "Par la porte arrière",
    "th16_13": "Les Quatre Saisons Cachées",
    "th16_14": "Plus de passage par les portes",
    "th16_15": "Éternelle et Parfaite Floraison ~ Vie Cachée Parmis les Spectres",
    "th16_16": "Nature non naturelle",
    "th16_17": "Voyageur blanc",
    "th16_18": "Score du joueur",
}