{
	"0": "« Exponentialité alternative »",
	"2": "« Une jeune fille au QI d'or »",
	"4": "« Une jeune déesse au QI d'or »",
	"6": "Programme « Trou de Ver Virtuel »",
	"10": "Signe du gras : « Butter Spark »",
    "12": "Signe du gras : « Sweet Butter Spark »",
    "14": "Rébellion : « Orbes du passé »",
    "18": "Magie normande « Crise du Mont Saint-Michel »",
    "21": "Magie normande : « Shoot the Bretagne »",
	"22": "Art divin : « Art de la couture »",
    "24": "Art divin : « Art de la couture de poupées »",
	"26": "Signe primitif : « Être mono-neuronal »",
    "28": "Signe primitif : « Être bi-neuronal »",
    "29": "Signe primitif : « Neurone unique et infini »",
	"30": "Destruction : « Hakai »",
    "32": "Destruction : « ALL FICTION »",
	"34": "Signe du chaos : « Floraison imprévue »",
    "36": "Signe du chaos : « Floraison imprévue et fatale »",
    "37": "Signe du chaos : « Fleurs d'annihilation »",
    "38": "« A vaincre sans péril, on triomphe sans gloire »",
	"42": "Signe de la chaleur « Cuisson lente »",
    "46": "Signe de la vapeur « Étreinte Furtive »",
    "50": "Changement d'état « Ébullition »",
    "54": "« Lumière guidant au zéro absolu »",
	"58": "Mensonge « La mort de Nozomia »",
    "60": "Mensonge « Peut-on couper les fils du destin ? »",
	"62": "Pyrotechnie : « Feu d'artifice bizarre de Charlotte »",
    "64": "Pyrotechnie : « Feu d'artifice illusoire parfait »",
	"66": "Signe sacré : « Barrière de purification de la Besta »",
	"69": "Signe sacré : « La pure flamme de la vérité »",
    "70": "Décor : « Lune explosive »",
	"74": "« Rupture de l'illusion »",
    "76": "« Tonnerre d'applaudissements »",
    "78G": "Savoir-faire : « Production de divin sel »",
    "78S": "Savoir-faire : « Production de beurre pur »",
    "82G": "Signe du Non-Beurre : « Sonar salé de Brest »",
    "82S": "Signe du Non-Beurre : « Pont doux de Tancarville »",
	"86G": "« Étendard d'une faction bretonne »",
	"86S": "« Champ de menhirs normand »",
    "88G": "« Symbole de l'ordre traditionnel »",
	"88S": "« Terre de mémoires ancestrales »",
    "90G": "« Bénédiction du kouign amann »",
	"90S": "« Protection du Mont Saint-Michel »",
	"94G": "Autorité Divine « Grand Ordre du Beurre Salé »",
	"94S": "Autorite Divine « Grand Ordre du Beurre Doux »",
    "98G": "« Tempête divine »",
	"98S": "« Rayonnement divin »",
    "101G": "« Il ne pleut que sur les cons »",
	"101S": "« La lumière projette des ombres »",
    "102G": "Signe du beurre : « Praises of Salted Heavens »",
	"102S": "Signe du beurre : « Praises of Soft Heavens »",
    "104G": "Signe du beurre : « Une prière à la déesse cristalline »",
	"104S": "Signe du beurre : « Une prière à la déesse sobre »",
	"106": "Probabilité « Arbre monde de possibilités »",
	"107": "« Ta gueule, c'est mathématique »",
	"108": "« Mémoires de la haine et de la destruction »",
	"109": "Signe Impie « Lances Écarlates de l'Hérétique »",
	"110": "Illusion : « La vérité cruelle derrière le roman »",
    "111": "Karaoké : « DEMONIC TRUTH »",
    "112": "Préparation « Couteau cérémoniel de Laguiole »",
    "113": "Mélange : « Battre la magie pour qu'elle soit homogène »",
    "114": "Signe de la poêle : « Cuisson parfaite »",
    "115": "Démon : « Le grand banquet des vampires »",
    "116": "Déesse « Plat du jour du restaurant Kurakomainu »",
    "117": "« Facts of Buttered Landings »",
    "118": "« Ultime danmaku d'un conte beurré »"
}